//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// Sazabi.rc で使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDM_APP_EXIT                    0x0020
#define IDM_TASK_MGR                    0x0040
#define IDR_MAINFRAME                   128
#define IDR_SGSECITYPE                  129
#define IDS_STRING_DLG1                 130
#define IDD_DIALOG2                     131
#define IDS_STRING_DLG2                 132
#define IDS_STRING_DLG3                 133
#define IDS_STRING_FRM1                 134
#define IDS_STRING_FRM2                 135
#define IDR_HTML_DLGEULA                136
#define IDS_STRING_FRM3                 137
#define IDS_STRING_CEF_LIC              138
#define IDS_STRING_FAV_NAME             139
#define IDS_STRING_CEF_LOCALE           140
#define IDS_STRING_CEF_ACCEPT_LANGUAGE_LIST 141
#define IDD_DLG_PROGRESS                142
#define IDS_PROPRIETARY_CODEC_LICENSES  142
#define IDS_STRING_PROPRIETARY_CODEC_LICENSES 142
#define IDR_MENU_BACK                   143
#define IDR_MENU_FORWARD                144
#define IDB_BITMAP3                     146
#define IDI_ICON1                       147
#define IDB_COLDTOOLBAR                 150
#define IDB_HOTTOOLBAR                  151
#define IDR_TOOLBAR1                    152
#define IDB_BITMAP4                     153
#define IDB_BITMAP1                     155
#define IDD_DIALOG3                     156
#define IDB_CLOSE                       157
#define IDB_MAX                         159
#define IDB_MIN                         160
#define IDD_SETTINGS_DLG_URL_FILTER     161
#define IDS_STRING_CLOSE_ALL_WINDOW     162
#define IDS_STRING_ADMIN_LOCK_FEATURE   163
#define IDS_STRING_EVALUATION           164
#define IDS_STRING_EVALUATION_THANKS    165
#define IDS_STRING_ZONE_MSG_DBL         167
#define IDS_STRING_ZONE_MSG_NG          168
#define IDD_SETTINGS_DLG                171
#define IDD_SETTINGS_DLG_LOG            172
#define IDD_SETTINGS_DLG_DSP            173
#define IDD_SETTINGS_DLG_SEC            174
#define IDD_SETTINGS_DLG_INIT           184
#define IDD_SETTINGS_DLG_FILEMGR        185
#define IDS_STRING_ZONE_MSG_IE          186
#define IDD_DLG_AUTH                    187
#define IDS_STRING_ZONE_MSG_FF          188
#define IDB_BITMAP2                     189
#define IDB_BMP_KEY                     190
#define IDS_STRING_ZONE_MSG_CHR         191
#define IDS_STRING_ZONE_MSG_EDG         193
#define IDD_DLG_DOWNLOAD                194
#define IDD_DLG_DEBUG_WND               195
#define IDB_BMP_DL                      196
#define IDS_STRING_ZONE_MSG_CUSTOM      197
#define IDB_BITMAP5                     198
#define IDS_STRING_DISABLE_EXEC         199
#define IDR_MENU1                       200
#define IDR_MENU_TAB                    201
#define IDB_BITMAP6                     202
#define IDD_DLG_SC_EDITOR               203
#define IDD_SETTINGS_DLG_CONNECTION     204
#define IDS_STRING_AUTO_RECOVERY        205
#define IDD_SETTINGS_DLG_GEN            206
#define IDS_STRING_UNDO                 207
#define IDD_SETTINGS_DLG_CAP            208
#define IDS_STRING_CUT                  209
#define IDS_STRING_COPY                 210
#define IDS_STRING_PASTE                211
#define IDS_STRING_DELETE               212
#define IDS_STRING_SELECTALL            213
#define IDS_STRING_PASTE_GO             214
#define IDS_STRING_PASTE_SEARCH         215
#define IDS_STRING_GO                   216
#define IDS_STRING_SEARCH               217
#define IDS_STRING_SEL_SEARCH           218
#define IDS_STRING_OPEN_NOACTIVE        219
#define IDS_STRING_SETTINGS             220
#define IDD_DLG_DOMAIN                  221
#define IDD_SETTINGS_DLG_CUSTOM_SCRIPT  222
#define IDD_DLG_CUSTOMSCRIPT            223
#define IDD_DLG_AUTH_PWC                224
#define IDI_ICON2                       225
#define IDI_ICON3                       226
#define IDS_STRING_STARTING_BROWSER     227
#define IDS_STRING_SETTINGS_DLG_TITLE_GEN 228
#define IDS_STRING_SETTINGS_DLG_TITLE_DSP 229
#define IDS_STRING_SETTINGS_DLG_TITLE_INIT 230
#define IDS_STRING_SETTINGS_DLG_TITLE_CONNECTION 231
#define IDS_STRING_SETTINGS_DLG_TITLE_CAP 232
#define IDS_STRING_SETTINGS_DLG_TITLE_SEC 233
#define IDS_STRING_SETTINGS_DLG_TITLE_URL_FILTER 234
#define IDS_STRING_SETTINGS_DLG_TITLE_CUSTOM_SCRIPT 235
#define IDS_STRING_SETTINGS_DLG_TITLE_LOG 236
#define IDS_STRING_SETTINGS_DLG_TITLE_FILEMGR 237
#define ID_SETTINGS_COLUMN_HEADER_URL   238
#define ID_SETTINGS_COLUMN_HEADER_DOMAIN 239
#define ID_SETTINGS_COLUMN_HEADER_FILE  240
#define ID_SETTINGS_COLUMN_HEADER_ACTION 241
#define ID_SETTINGS_COLUMN_HEADER_ENABLED 242
#define ID_SETTINGS_MENU_LABEL          243
#define IDS_STRING_CONFIRM_CANCEL_DOWNLOAD 244
#define IDS_STRING_WELCOME_MSG          245
#define IDS_STRING_STARTING_FILEMGR     246
#define IDS_STRING_CONFIRM_CLEAR_CACHE  247
#define IDS_STRING_STARTING_NEW_SESSION 248
#define ID_OPEN_FILE_CHOOSER_TITLE      249
#define ID_MSG_FILE_DOWNLOAD_RESTRICTED 250
#define ID_MSG_ANOTHER_DOWNLOAD_IN_PROGRESS 251
#define ID_DEFAULT_FILE_BASENAME        252
#define ID_FILE_TYPE_ALL                253
#define ID_FILE_TYPE_PDF                254
#define ID_FILE_TYPE_EXE                255
#define ID_FILE_TYPE_JS                 256
#define ID_DOWNLOAD_FILE_CHOOSER_TITLE  257
#define ID_PRINT_TO_PDF_FILE_CHOOSER_TITLE 258
#define ID_DEFAULT_FILE_DOWNLOAD_WINDOW_TITLE 259
#define ID_PRINT_TO_PDF_FINISH_MSG      260
#define ID_DOWNLOAD_PROGRESS_DIALOG_TITLE 261
#define ID_TRANSFER_SPEED_B             262
#define ID_TRANSFER_SPEED_KB            263
#define ID_TRANSFER_SPEED_MB            264
#define ID_TRANSFER_SIZE_UNDETERMINED   265
#define ID_TRANSFER_PROGRESS_MSG        267
#define ID_CONFIRM_CANCEL_DOWNLOAD      268
#define ID_DL_START_APP_IN_PROGRESS     269
#define ID_DL_START_APP_FAILED_BASE     270
#define ID_DL_START_APP_FAILED_LOW_RESOURCE 271
#define ID_DL_START_APP_FAILED_FILE_NOT_FOUND 272
#define ID_DL_START_APP_FAILED_PATH_NOT_FOUND 273
#define ID_DL_START_APP_FAILED_BAD_FORMAT 274
#define ID_DL_START_APP_FAILED_ACCESSDENIED 275
#define ID_DL_START_APP_FAILED_ASSOCINCOMPLETE 276
#define ID_DL_START_APP_FAILED_DDEBUSY  277
#define ID_DL_START_APP_FAILED_DDEFAIL  278
#define ID_DL_START_APP_FAILED_DDETIMEOUT 279
#define ID_DL_START_APP_FAILED_DLLNOTFOUND 280
#define ID_DL_START_APP_FAILED_NOASSOC  281
#define ID_DL_START_APP_FAILED_OOM      282
#define ID_DL_START_APP_FAILED_SHARE    283
#define ID_DL_START_APP_FAILED_DEFAULT  284
#define ID_DOWNLOAD_COMPLETE_DIALOG_CLOSE 285
#define ID_DOWNLOAD_COMPLETE_DIALOG_TITLE 286
#define IDS_STRING_HOST_AUTH_REQUIRED   287
#define IDS_STRING_PROXY_AUTH_REQUIRED  288
#define IDS_STRING_CONFIRM_INSECURE_CONNECTION 289
#define IDS_STRING_CONFIRM_LEAVE_PAGE   290
#define IDS_STRING_ALERT_MISSING_FILES  291
#define IDS_STRING_CLEARING_CACHE       292
#define IDS_STRING_CONFIRM_CLOSE_APPLICATION 293
#define IDS_STRING_TOO_MANY_WINDOWS_MSG 294
#define IDS_STRING_LOW_SYSTEM_RESOURCE_EXIT 295
#define IDS_STRING_LOW_SYSTEM_RESOURCE_SHUTDOWN 296
#define IDS_STRING_LOW_SYSTEM_RESOURCE_SUGGEST 297
#define IDS_STRING_CONFIRM_CLOSE_VOS_PROCESS 298
#define ID_CONTEXT_MENU_OPEN_LINK_TAB   299
#define ID_CONTEXT_MENU_OPEN_LINK_TAB_INACTIVE 300
#define ID_CONTEXT_MENU_OPEN_LINK_WINDOW 301
#define ID_CONTEXT_MENU_OPEN_LINK_WINDOW_INACTIVE 302
#define ID_CONTEXT_MENU_COPY_LINK       303
#define ID_CONTEXT_MENU_SAVE_LINK       304
#define ID_CONTEXT_MENU_OPEN_IMG_TAB    305
#define ID_CONTEXT_MENU_OPEN_IMG_TAB_INACTIVE 306
#define ID_CONTEXT_MENU_OPEN_IMG_WINDOW 307
#define ID_CONTEXT_MENU_OPEN_IMG_WINDOW_INACTIVE 308
#define ID_CONTEXT_MENU_SAVE_IMG        309
#define ID_CONTEXT_MENU_COPY_IMG        310
#define ID_CONTEXT_MENU_COPY_IMG_LINK   311
#define ID_CONTEXT_MENU_SEARCH          312
#define ID_CONTEXT_MENU_RELOAD          313
#define ID_CONTEXT_MENU_PRINT_PDF       314
#define ID_CONTEXT_MENU_PRINT           315
#define ID_ERROR_MSG_FAILED             316
#define ID_ERROR_MSG_NONE               317
#define ID_ERROR_MSG_ABORTED            318
#define ID_ERROR_MSG_INVALID_ARGUMENT   319
#define ID_ERROR_MSG_INVALID_HANDLE     320
#define ID_ERROR_MSG_FILE_NOT_FOUND     321
#define ID_ERROR_MSG_TIMED_OUT          322
#define ID_ERROR_MSG_FILE_TOO_BIG       323
#define ID_ERROR_MSG_UNEXPECTED         324
#define ID_ERROR_MSG_ACCESS_DENIED      325
#define ID_ERROR_MSG_NOT_IMPLEMENTED    326
#define ID_ERROR_MSG_CONNECTION_CLOSED  327
#define ID_ERROR_MSG_CONNECTION_RESET   328
#define ID_ERROR_MSG_CONNECTION_REFUSED 329
#define ID_ERROR_MSG_CONNECTION_ABORTED 330
#define ID_ERROR_MSG_CONNECTION_FAILED  331
#define ID_ERROR_MSG_NAME_NOT_RESOLVED  332
#define ID_ERROR_MSG_INTERNET_DISCONNECTED 333
#define ID_ERROR_MSG_SSL_PROTOCOL_ERROR 334
#define ID_ERROR_MSG_ADDRESS_INVALID    335
#define ID_ERROR_MSG_ADDRESS_UNREACHABLE 336
#define ID_ERROR_MSG_SSL_CLIENT_AUTH_CERT_NEEDED 337
#define ID_ERROR_MSG_TUNNEL_CONNECTION_FAILED 338
#define ID_ERROR_MSG_NO_SSL_VERSIONS_ENABLED 339
#define ID_ERROR_MSG_SSL_VERSION_OR_CIPHER_MISMATCH 340
#define ID_ERROR_MSG_SSL_RENEGOTIATION_REQUESTED 341
#define ID_ERROR_MSG_CERT_COMMON_NAME_INVALID 342
#define ID_ERROR_MSG_CERT_DATE_INVALID  343
#define ID_ERROR_MSG_CERT_AUTHORITY_INVALID 344
#define ID_ERROR_MSG_CERT_CONTAINS_ERRORS 345
#define ID_ERROR_MSG_CERT_NO_REVOCATION_MECHANISM 346
#define ID_ERROR_MSG_CERT_UNABLE_TO_CHECK_REVOCATION 347
#define ID_ERROR_MSG_CERT_REVOKED       348
#define ID_ERROR_MSG_CERT_INVALID       349
#define ID_ERROR_MSG_CERT_WEAK_SIGNATURE_ALGORITHM 350
#define ID_ERROR_MSG_CERT_NON_UNIQUE_NAME 351
#define ID_ERROR_MSG_CERT_WEAK_KEY      352
#define ID_ERROR_MSG_CERT_NAME_CONSTRAINT_VIOLATION 353
#define ID_ERROR_MSG_CERT_VALIDITY_TOO_LONG 354
#define ID_ERROR_MSG_INVALID_URL        355
#define ID_ERROR_MSG_DISALLOWED_URL_SCHEME 356
#define ID_ERROR_MSG_UNKNOWN_URL_SCHEME 357
#define ID_ERROR_MSG_TOO_MANY_REDIRECTS 358
#define ID_ERROR_MSG_UNSAFE_REDIRECT    359
#define ID_ERROR_MSG_UNSAFE_PORT        360
#define ID_ERROR_MSG_INVALID_RESPONSE   361
#define ID_ERROR_MSG_INVALID_CHUNKED_ENCODING 362
#define ID_ERROR_MSG_METHOD_NOT_SUPPORTED 363
#define ID_ERROR_MSG_UNEXPECTED_PROXY_AUTH 364
#define ID_ERROR_MSG_EMPTY_RESPONSE     365
#define ID_ERROR_MSG_RESPONSE_HEADERS_TOO_BIG 366
#define ID_ERROR_MSG_CACHE_MISS         367
#define ID_ERROR_MSG_INSECURE_RESPONSE  368
#define ID_ERROR_MSG_PROXY_CONNECTION_FAILED 369
#define ID_ERROR_PAGE_TITLE             370
#define ID_ERROR_PAGE_HEADING           371
#define ID_ERROR_PAGE_HEADING_DETAILS   372
#define ID_ERROR_PAGE_HEADING_URL       373
#define ID_ERROR_PAGE_HEADING_CODE      374
#define ID_ERROR_PAGE_HEADING_MSG       375
#define ID_ERROR_PAGE_HEADING_NAME      376
#define ID_ERROR_MISMATCHED_PARAMETER   377
#define ID_ALERT_CANNOT_SAVE_CONFIGS    378
#define ID_KEY_COMBINATION_EMPTY        379
#define ID_KEY_COMBINATION_CONFIRM      380
#define ID_KEY_COMBINATION_SUCCEEDED    381
#define ID_KEY_COMBINATION_FAILED       382
#define ID_ACTION_LABEL_ALLOW           383
#define ID_ACTION_LABEL_DENY            384
#define ID_CANNOT_SAVE_URL_FILTER       385
#define ID_CANNOT_LOAD_CUSTOM_SCRIPT    386
#define ID_CANNOT_SAVE_CUSTOM_SCRIPT    387
#define ID_ALERT_ALREADY_ADDED_DOMAIN   388
#define ID_ALERT_ALREADY_ADDED_URL_OR_FILE 389
#define ID_ALERT_EMPTY_URL              390
#define ID_ALERT_EMPTY_FILENAME         391
#define ID_ALERT_EMPTY_DOMAIN           392
#define ID_INFO_DLG_LIST_HIDE           393
#define ID_INFO_DLG_LIST_0_5            394
#define ID_INFO_DLG_LIST_1_0            395
#define ID_INFO_DLG_LIST_1_5            396
#define ID_INFO_DLG_LIST_2_0            397
#define ID_INFO_DLG_LIST_2_5            398
#define ID_INFO_DLG_LIST_3_0            399
#define ID_INFO_DLG_LIST_3_5            400
#define ID_INFO_DLG_LIST_4_0            401
#define ID_INFO_DLG_LIST_4_5            402
#define ID_INFO_DLG_LIST_5_0            403
#define ID_INFO_DLG_LIST_5_5            404
#define ID_INFO_DLG_LIST_6_0            405
#define ID_INFO_DLG_LIST_6_5            406
#define ID_INFO_DLG_LIST_7_0            407
#define ID_INFO_DLG_LIST_7_5            408
#define ID_INFO_DLG_LIST_8_0            409
#define ID_INFO_DLG_LIST_8_5            410
#define ID_INFO_DLG_LIST_9_0            411
#define ID_INFO_DLG_LIST_9_5            412
#define ID_INFO_DLG_LIST_10_0           413
#define ID_INFO_OPEN_OPTION_HIDE_MARK_AS_OPENED 414
#define ID_INFO_OPEN_OPTION_SHOW_MARK_AS_OPENED 415
#define ID_INFO_OPEN_OPTION_SHOW_TRANSFER 416
#define ID_MISSING_PROXY_CONFIG         417
#define ID_URL_REDIRECT_SCRIPT_HELP     418
#define ID_URL_REDIRECT_SCRIPT_TRACE_LOG_DEFAULT 419
#define ID_AUTH_ALERT_EMPTY_USER        420
#define ID_AUTH_REQUIRED                421
#define ID_AUTH_ALERT_MISMATCHED_PASSWORD 422
#define ID_AUTH_CHANGE_PASSWORD         423
#define ID_DEBUG_ITEMS_COUNT            424
#define ID_DEBUG_LINES_COUNT            425
#define ID_DEBUG_CONFIRM_SAVE_RESULT    426
#define ID_DEBUG_ALERT_SAVE_FAILED      427
#define IDS_STRING_ALERT_OVER_RUNNING_TIME_LIMIT 428
#define ID_ENABLE_MEDIA_CONFIRMATION    429
#define ID_ENABLE_MEDIA_MIC             430
#define ID_ENABLE_MEDIA_VIDEO           431
#define ID_ENABLE_MEDIA_DESKTOP_AUDIO   432
#define ID_ENABLE_MEDIA_DESKTOP_VIDEO   433
#define IDD_DLG_CERTIFICATION           434
#define ID_CERTIFICATION_ISSUER         435
#define ID_CERTIFICATION_SUBJECT        436
#define ID_CERTIFICATION_SERIAL_NUMBER  437
#define IDS_CERTIFICATION_VALID_PERIOD  438
#define ID_CERTIFICATION_VALID_PERIOD   438
#define IDC_EDIT1                       1000
#define IDC_EDIT_PW                     1001
#define IDC_EDIT2                       1002
#define IDC_CHECK1                      1006
#define IDC_B_SETTING                   1007
#define IDC_STATIC_LOGO                 1008
#define IDC_CHECK_ENABLE_LOG            1011
#define IDC_RADIO_LOG_ALL               1012
#define IDC_RADIO_LOG_NOFILE            1013
#define IDC_RADIO_LOG_GE_URL            1014
#define IDC_RADIO1                      1015
#define IDC_STATIC_TL                   1016
#define IDC_ExtFilter                   1017
#define IDC_EDIT_ZOOM                   1018
#define IDC_ShowUploadTab               1019
#define IDC_CHECK_ENABLE_CUSTOM_SCRIPT  1020
#define IDC_UploadSyncInterval          1021
#define IDC_EnableOpendOp               1022
#define IDC_EnableUploadSync            1023
#define IDC_EDIT_PW_NEW                 1024
#define IDC_EDIT_PW_NEW2                1025
#define IDC_EDIT_INIT_MSG               1026
#define IDC_CHECK_ENABLE_AUTO_ADJUST_WINPOS 1027
#define IDC_EDIT_W                      1030
#define IDC_EDIT_H                      1031
#define IDC_STATIC_MSG                  1032
#define IDC_EDIT_ID                     1033
#define IDC_EDIT_BW_LIST                1034
#define IDC_STATIC_FN                   1035
#define IDC_STATIC_TX                   1036
#define IDC_PROGRESS1                   1037
#define IDC_RADIO2                      1038
#define IDC_RootPath                    1039
#define IDC_STATIC_DL_MSG               1040
#define IDC_DisallowExt                 1041
#define IDC_TransferPath                1042
#define IDC_TransferSubFolder           1043
#define IDC_UploadPath                  1044
#define IDC_EDIT_SEARCH                 1045
#define IDC_DisableOpendOpAlert         1046
#define IDC_SetShowUploadTab            1047
#define IDC_EDIT_PW_CURRENT             1048
#define IDC_CHECK_DISABLE_MULTIPLE_INSTANCE 1049
#define IDC_EnableUploadSyncMirror      1050
#define IDC_EDIT_INIT_URL_PARAM         1052
#define IDC_EDIT_INIT_OP_PARAM          1053
#define IDC_CHECK_SHOW_PRINTER_BUTTON   1054
#define IDC_CHECK_GPU                   1055
#define IDC_CHECK_TAB                   1056
#define IDC_CHECK_LOGO                  1057
#define IDC_CHECK_PDF                   1058
#define IDC_CHECK_DISABLE_REBAR         1059
#define IDC_CHECK_DISABLE_STATUSBAR     1060
#define IDC_CHECK_DISABLE_STATUS_ICON   1061
#define IDC_CHECK_FLASH                 1062
#define IDC_CHECK_DISABLE_FILE_NAVIGATION 1065
#define IDC_COMBO1                      1084
#define IDC_BUTTON_FUNC                 1089
#define IDC_BUTTON_URL                  1090
#define IDC_BUTTON_TOP                  1091
#define IDC_BUTTON_TB_TRACE_LOG         1093
#define IDC_CERTIFICATION_EDIT          1094
#define IDC_CERTIFICATION_COMBO         1095
#define IDC_CERTIFICATE_STATIC_SITE_INFO 1096
#define IDC_PAGE_FRAME                  1200
#define IDC_TREE_CTRL                   1201
#define IDC_CAPTION_BAR                 1202
#define ID_INDICATOR_ICON               1250
#define ID_INDICATOR_PROCESS            1251
#define ID_INDICATOR_SSL                1252
#define ID_INDICATOR_ZONE               1253
#define ID_INDICATOR_COMPAT             1254
#define ID_INDICATOR_ZOOM               1255
#define IDC_CHK_SHIFT                   1257
#define IDC_CHK_CTRL                    1258
#define IDC_CHK_ALT                     1259
#define IDC_CHK_LEFT                    1260
#define IDC_CHK_UP                      1261
#define IDC_CHK_RIGHT                   1262
#define IDC_CHK_DOWN                    1263
#define IDC_BUTTON1                     1264
#define IDC_BUTTON_FO                   1265
#define IDC_BUTTON_DIRO                 1266
#define IDC_RAD_PX_IE                   1267
#define IDC_RAD_PX_NA                   1268
#define IDC_RAD_PX_EF                   1269
#define IDC_EDIT_ProxyAddress           1270
#define IDC_EDIT_ProxyBypassAddress     1271
#define IDC_CHECK_ENABLE_URL_FILTER     1272
#define IDC_LIST1                       1273
#define IDC_BUTTON_INS                  1274
#define IDC_BUTTON_DEL                  1275
#define IDC_BUTTON_UP                   1276
#define IDC_BUTTON_DOWN                 1277
#define IDC_STATIC_LINE                 1278
#define IDC_UserAgentAppendStr          1279
#define IDC_MemoryUsageWarning          1280
#define IDC_MemoryUsageLimit            1281
#define IDC_WindowCountWarning          1282
#define IDC_CHECK_ENABLECRASHRECOVERY   1328
#define IDC_ENABLE_MEMCACHE             1340
#define IDC_Enable_ProcessRunTime       1344
#define IDC_EDIT_LIMIT_TIME             1345
#define IDC_VOS_CLOSE_PROCESS           1346
#define IDC_EnableUploadRestriction     1346
#define IDC_SHOW_DEV_TOOLS              1347
#define IDC_EnableDownloadRestriction   1347
#define IDC_EDIT_CustomBrowser1         1348
#define IDC_EnableDeleteCache           1348
#define IDC_CEF_VERSION                 1348
#define IDC_CHECK_EnableZoneFilterScript 1349
#define IDC_BUTTON_BROWSE1              1350
#define IDC_BUTTON_SCRIPT_EDIT          1351
#define IDC_EDIT_CustomBrowser2         1352
#define IDC_BUTTON_BROWSE2              1353
#define IDC_EDIT_CustomBrowser3         1354
#define IDC_BUTTON_BROWSE3              1355
#define IDC_EDIT_CustomBrowser4         1356
#define IDC_BUTTON_BROWSE4              1357
#define IDC_EDIT_CustomBrowser5         1358
#define IDC_BUTTON_BROWSE5              1359
#define IDC_WindowCountLimit            1360
#define IDC_STATIC_LOGO_ABOUT           1361
#define IDC_CHECK_EnableLogging         1362
#define IDC_EDIT_LogServerURL           1363
#define IDC_RADIO_LOG_GET               1364
#define IDC_RADIO_LOG_POST              1365
#define IDC_CHECK_ENABLE_DOWNLOAD_LOG   1366
#define IDC_CHECK_ENABLE_UPLOAD_LOG     1367
#define IDC_CHECK_EnableBrowsingLogging 1368
#define IDC_CHECK_EnableAccessAllLogging 1369
#define IDC_EDIT_RequestHeader          1370
#define ID_SETTINGS                     32609
#define IDD_ABOUTBOX                    32771
#define ID_NEW                          32772
#define ID_PRINT                        32773
#define ID_LOGIN                        32774
#define ID_GO_BACK                      32776
#define ID_GO_FORWARD                   32777
#define ID_VIEW_STOP                    32778
#define ID_VIEW_REFRESH                 32779
#define ID_GO_START_PAGE                32780
#define ID_OPEN                         32781
#define ID_SHOW_DEVTOOLS                32782
#define ID_PRINT_PDF                    32783
#define ID_CUT                          32784
#define ID_COPY                         32785
#define ID_PASTE                        32786
#define ID_SEL_ALL                      32787
#define ID_FIND_PAGE                    32788
#define ID_SET_ADDRESSBAR               32797
#define ID_NEW_SESSION                  32798
#define ID_SET_SEARCHBAR                32799
#define ID_FAVORITE_ADD                 32802
#define ID_FAVORITE_ORGANIZE            32803
#define ID_FAVORITE_DUMMY               32804
#define ID_ADD_FAVORITE                 32805
#define ID_ORGANIZE_FAVORITE            32806
#define ID_BF_BACK1                     32807
#define ID_BF_BACK2                     32808
#define ID_BF_BACK3                     32809
#define ID_BF_BACK4                     32810
#define ID_BF_BACK5                     32811
#define ID_BF_BACK6                     32812
#define ID_BF_BACK7                     32813
#define ID_BF_BACK8                     32814
#define ID_BF_BACK9                     32815
#define ID_BF_BACK_END                  32816
#define ID_CLOSE_WND_HISTORY_DUMMY      32818
#define ID_BF_FORWARD1                  32820
#define ID_BF_FORWARD2                  32821
#define ID_BF_FORWARD3                  32822
#define ID_BF_FORWARD4                  32823
#define ID_BF_FORWARD5                  32824
#define ID_BF_FORWARD6                  32825
#define ID_BF_FORWARD7                  32826
#define ID_BF_FORWARD8                  32827
#define ID_BF_FORWARD9                  32828
#define ID_BF_FORWARD_END               32829
#define ID_FILE_SAVEAS                  32847
#define ID_FULL_SCREEN                  32849
#define ID_W_CLOSE                      32850
#define ID_PREV_WND                     32853
#define ID_NEXT_WND                     32854
#define IDC_APP_EXIT                    32857
#define IDC_APP_EXIT_BUT_THIS           32858
#define ID_WINDOW_DUMMY                 32859
#define ID_CASCADE_WND                  32860
#define ID_TILE_V_WND                   32861
#define ID_TILE_H_WND                   32862
#define ID_MAXIMIZE_V_WND               32863
#define ID_MAXIMIZE_H_WND               32864
#define ID_MINIMIZE_ALL                 32865
#define ID_TOPMOST_WND                  32866
#define ID_TOPMOST_REL_WND              32867
#define ID_TOPMOST_SET                  32868
#define ID_RESTORE_WND                  32869
#define ID_SAVE_WND                     32870
#define ID_OPEN_THIN_FILER              32871
#define ID_NEW_BLANK                    32872
#define ID_TAB_CLOSE_RIGHT              32873
#define ID_TAB_CLOSE_LEFT               32874
#define ID_NEW_BLANK_TAB                32875
#define ID_TAB_LIST                     32876
#define ID_REOPEN_CLOSE_TAB             32877
#define ID_ZOOM_START                   32900
#define ID_ZOOM_END                     33000
#define ID_SEL_TAB_1                    33001
#define ID_SEL_TAB_2                    33002
#define ID_SEL_TAB_3                    33003
#define ID_SEL_TAB_4                    33004
#define ID_SEL_TAB_5                    33005
#define ID_SEL_TAB_6                    33006
#define ID_SEL_TAB_7                    33007
#define ID_SEL_TAB_8                    33008
#define ID_SEL_TAB_LAST                 33009
#define ID_ZOOM_UP                      33010
#define ID_ZOOM_DOWN                    33011
#define ID_ZOOM_RESET                   33012
#define IDC_APP_DELETE_CACHE            33013
#define ID_SETTING_OK                   36610

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        439
#define _APS_NEXT_COMMAND_VALUE         33015
#define _APS_NEXT_CONTROL_VALUE         1097
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
