//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// Sazabi.rc で使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDM_APP_EXIT                    0x0020
#define IDM_TASK_MGR                    0x0040
#define IDR_MAINFRAME                   128
#define IDR_SGSECITYPE                  129
#define IDS_STRING_DLG1                 130
#define IDD_DIALOG2                     131
#define IDS_STRING_DLG2                 132
#define IDS_STRING_DLG3                 133
#define IDS_STRING_FRM1                 134
#define IDS_STRING_FRM2                 135
#define IDR_HTML_DLGEULA                136
#define IDS_STRING_FRM3                 137
#define IDS_STRING_CEF_LIC              138
#define IDS_STRING_FAV_NANE             139
#define IDD_DIALOG1                     140
#define IDR_MENU_BACK                   141
#define IDR_MENU_FORWARD                142
#define IDB_BITMAP3                     143
#define IDI_ICON1                       144
#define IDB_COLDTOOLBAR                 146
#define IDB_HOTTOOLBAR                  147
#define IDR_TOOLBAR1                    150
#define IDB_BITMAP4                     151
#define IDB_BITMAP1                     152
#define IDD_DIALOG3                     153
#define IDB_CLOSE                       155
#define IDB_MAX                         156
#define IDB_MIN                         157
#define IDD_SETTINGS_DLG_URL_FILTER     159
#define IDS_STRING_CLOSE_ALL_WINDOW     160
#define IDS_STRING_ADMIN_LOCK_FEATURE   161
#define IDS_STRING_EVALUATION           162
#define IDS_STRING_EVALUATION_THANKS    163
#define IDS_STRING_ZONE_MSG_DBL         164
#define IDS_STRING_ZONE_MSG_NG          165
#define IDD_SETTINGS_DLG                167
#define IDD_SETTINGS_DLG_LOG            168
#define IDD_SETTINGS_DLG_DSP            171
#define IDD_SETTINGS_DLG_SEC            172
#define IDD_SETTINGS_DLG_INIT           173
#define IDD_SETTINGS_DLG_FILEMGR        174
#define IDS_STRING_ZONE_MSG_IE          184
#define IDD_DLG_AUTH                    185
#define IDS_STRING_ZONE_MSG_FF          186
#define IDB_BITMAP2                     187
#define IDB_BMP_KEY                     188
#define IDS_STRING_ZONE_MSG_CHR         189
#define IDS_STRING_ZONE_MSG_EDG         190
#define IDD_DIALOG4                     191
#define IDD_DLG_DEBUG_WND               193
#define IDB_BMP_DL                      194
#define IDS_STRING_ZONE_MSG_CUSTOM      195
#define IDB_BITMAP5                     196
#define IDS_STRING_DISABLE_EXEC         197
#define IDR_MENU1                       198
#define IDR_MENU_TAB                    199
#define IDB_BITMAP6                     200
#define IDD_DLG_SC_EDITOR               201
#define IDD_SETTINGS_DLG_CONNECTION     202
#define IDS_STRING_AUTO_RECOVERY        203
#define IDD_SETTINGS_DLG_GEN            204
#define IDS_STRING_UNDO                 205
#define IDD_SETTINGS_DLG_CAP            206
#define IDS_STRING_CUT                  207
#define IDS_STRING_COPY                 208
#define IDS_STRING_PASTE                209
#define IDS_STRING_DELETE               210
#define IDS_STRING_SELECTALL            211
#define IDS_STRING_PASTE_GO             212
#define IDS_STRING_PASTE_SEARCH         213
#define IDS_STRING_GO                   214
#define IDS_STRING_SEARCH               215
#define IDS_STRING_SEL_SEARCH           216
#define IDS_STRING_OPEN_NOACTIVE        217
#define IDS_STRING_SETTINGS             218
#define IDD_DIALOG5                     219
#define IDD_SETTINGS_DLG_CUSTOM_SCRIPT  220
#define IDD_DIALOG6                     221
#define IDD_DLG_AUTH_PWC                222
#define IDI_ICON2                       223
#define IDI_ICON3                       224
#define IDS_STRING_SETTINGS_DLG_TITLE_GEN           225
#define IDS_STRING_SETTINGS_DLG_TITLE_DSP           226
#define IDS_STRING_SETTINGS_DLG_TITLE_INIT          227
#define IDS_STRING_SETTINGS_DLG_TITLE_CONNECTION    228
#define IDS_STRING_SETTINGS_DLG_TITLE_CAP           229
#define IDS_STRING_SETTINGS_DLG_TITLE_SEC           230
#define IDS_STRING_SETTINGS_DLG_TITLE_URL_FILTER    231
#define IDS_STRING_SETTINGS_DLG_TITLE_SUSTOM_SCRIPT 232
#define IDS_STRING_SETTINGS_DLG_TITLE_LOG           233
#define IDS_STRING_SETTINGS_DLG_TITLE_FILEMGR       234
#define IDS_SETTINGS_COLUMN_HEADER_URL              235
#define IDS_SETTINGS_COLUMN_HEADER_DOMAIN           236
#define IDS_SETTINGS_COLUMN_HEADER_FILE             237
#define IDS_SETTINGS_COLUMN_HEADER_ACTION           238
#define IDS_SETTINGS_COLUMN_HEADER_ENABLED          239
#define IDC_EDIT1                       1000
#define IDC_EDIT_PW                     1001
#define IDC_EDIT2                       1002
#define IDC_CHECK1                      1006
#define IDC_B_SETTING                   1007
#define IDC_STATIC_LOGO                 1008
#define IDC_CHECK_ENABLE_LOG            1011
#define IDC_RADIO_LOG_ALL               1012
#define IDC_RADIO_LOG_NOFILE            1013
#define IDC_RADIO_LOG_GE_URL            1014
#define IDC_RADIO1                      1015
#define IDC_STATIC_TL                   1016
#define IDC_ExtFilter                   1017
#define IDC_EDIT_ZOOM                   1018
#define IDC_ShowUploadTab               1019
#define IDC_CHECK_ENABLE_CUSTOM_SCRIPT  1020
#define IDC_UploadSyncInterval          1021
#define IDC_EnableOpendOp               1022
#define IDC_EnableUploadSync            1023
#define IDC_EDIT_PW_NEW                 1024
#define IDC_EDIT_PW_NEW2                1025
#define IDC_EDIT_INIT_MSG               1026
#define IDC_CHECK_ENABLE_AUTO_ADJUST_WINPOS 1027
#define IDC_EDIT_W                      1030
#define IDC_EDIT_H                      1031
#define IDC_STATIC_MSG                  1032
#define IDC_EDIT_ID                     1033
#define IDC_EDIT_BW_LIST                1034
#define IDC_STATIC_FN                   1035
#define IDC_STATIC_TX                   1036
#define IDC_PROGRESS1                   1037
#define IDC_RADIO2                      1038
#define IDC_RootPath                    1039
#define IDC_STATIC_DL_MSG               1040
#define IDC_DisallowExt                 1041
#define IDC_TransferPath                1042
#define IDC_TransferSubFolder           1043
#define IDC_UploadPath                  1044
#define IDC_EDIT_SEARCH                 1045
#define IDC_DisableOpendOpAlert         1046
#define IDC_SetShowUploadTab            1047
#define IDC_EDIT_PW_CURRENT             1048
#define IDC_CHECK_DISABLE_MULTIPLE_INSTANCE 1049
#define IDC_EnableUploadSyncMirror      1050
#define IDC_EDIT_INIT_URL_PARAM         1052
#define IDC_EDIT_INIT_OP_PARAM          1053
#define IDC_CHECK_SHOW_PRINTER_BUTTON   1054
#define IDC_CHECK_GPU                   1055
#define IDC_CHECK_TAB                   1056
#define IDC_CHECK_LOGO                  1057
#define IDC_CHECK_PDF                   1058
#define IDC_CHECK_DISABLE_REBAR         1059
#define IDC_CHECK_DISABLE_STATUSBAR     1060
#define IDC_CHECK_DISABLE_STATUS_ICON   1061
#define IDC_CHECK_FLASH                 1062
#define IDC_CHECK_DISABLE_FILE_NAVIGATION 1065
#define IDC_COMBO1                      1084
#define IDC_BUTTON_FUNC                 1089
#define IDC_BUTTON_URL                  1090
#define IDC_BUTTON_TOP                  1091
#define IDC_BUTTON_TB_TRACE_LOG         1093
#define IDC_PAGE_FRAME                  1200
#define IDC_TREE_CTRL                   1201
#define IDC_CAPTION_BAR                 1202
#define ID_INDICATOR_ICON               1250
#define ID_INDICATOR_PROCESS            1251
#define ID_INDICATOR_SSL                1252
#define ID_INDICATOR_ZONE               1253
#define ID_INDICATOR_COMPAT             1254
#define ID_INDICATOR_ZOOM               1255
#define IDC_CHK_SHIFT                   1257
#define IDC_CHK_CTRL                    1258
#define IDC_CHK_ALT                     1259
#define IDC_CHK_LEFT                    1260
#define IDC_CHK_UP                      1261
#define IDC_CHK_RIGHT                   1262
#define IDC_CHK_DOWN                    1263
#define IDC_BUTTON1                     1264
#define IDC_BUTTON_FO                   1265
#define IDC_BUTTON_DIRO                 1266
#define IDC_RAD_PX_IE                   1267
#define IDC_RAD_PX_NA                   1268
#define IDC_RAD_PX_EF                   1269
#define IDC_EDIT_ProxyAddress           1270
#define IDC_EDIT_ProxyBypassAddress     1271
#define IDC_CHECK_ENABLE_URL_FILTER     1272
#define IDC_LIST1                       1273
#define IDC_BUTTON_INS                  1274
#define IDC_BUTTON_DEL                  1275
#define IDC_BUTTON_UP                   1276
#define IDC_BUTTON_DOWN                 1277
#define IDC_STATIC_LINE                 1278
#define IDC_UserAgentAppendStr          1279
#define IDC_MemoryUsageWarning          1280
#define IDC_MemoryUsageLimit            1281
#define IDC_WindowCountWarning          1282
#define IDC_CHECK_ENABLECRASHRECOVERY   1328
#define IDC_ENABLE_MEMCACHE             1340
#define IDC_Enable_ProcessRunTime       1344
#define IDC_EDIT_LIMIT_TIME             1345
#define IDC_VOS_CLOSE_PROCESS           1346
#define IDC_EnableUploadRestriction     1346
#define IDC_SHOW_DEV_TOOLS              1347
#define IDC_EnableDownloadRestriction   1347
#define IDC_EDIT_CustomBrowser1         1348
#define IDC_EnableDeleteCache           1348
#define IDC_CEF_VERSION                 1348
#define IDC_CHECK_EnableZoneFilterScript 1349
#define IDC_BUTTON_BROWSE1              1350
#define IDC_BUTTON_SCRIPT_EDIT          1351
#define IDC_EDIT_CustomBrowser2         1352
#define IDC_BUTTON_BROWSE2              1353
#define IDC_EDIT_CustomBrowser3         1354
#define IDC_BUTTON_BROWSE3              1355
#define IDC_EDIT_CustomBrowser4         1356
#define IDC_BUTTON_BROWSE4              1357
#define IDC_EDIT_CustomBrowser5         1358
#define IDC_BUTTON_BROWSE5              1359
#define IDC_WindowCountLimit            1360
#define IDC_STATIC_LOGO_ABOUT           1361
#define IDC_CHECK_EnableLogging         1362
#define IDC_EDIT_LogServerURL           1363
#define IDC_RADIO_LOG_GET               1364
#define IDC_RADIO_LOG_POST              1365
#define IDC_CHECK_ENABLE_DOWNLOAD_LOG   1366
#define IDC_CHECK_ENABLE_UPLOAD_LOG     1367
#define IDC_CHECK_EnableBrowsingLogging 1368
#define IDC_CHECK_EnableAccessAllLogging 1369
#define IDC_EDIT_RequestHeader          1370
#define ID_SETTINGS                     32609
#define IDD_ABOUTBOX                    32771
#define ID_NEW                          32772
#define ID_PRINT                        32773
#define ID_LOGIN                        32774
#define ID_GO_BACK                      32776
#define ID_GO_FORWARD                   32777
#define ID_VIEW_STOP                    32778
#define ID_VIEW_REFRESH                 32779
#define ID_GO_START_PAGE                32780
#define ID_OPEN                         32781
#define ID_SHOW_DEVTOOLS                32782
#define ID_PRINT_PDF                    32783
#define ID_CUT                          32784
#define ID_COPY                         32785
#define ID_PASTE                        32786
#define ID_SEL_ALL                      32787
#define ID_FIND_PAGE                    32788
#define ID_SET_ADDRESSBAR               32797
#define ID_NEW_SESSION                  32798
#define ID_SET_SEARCHBAR                32799
#define ID_FAVORITE_ADD                 32802
#define ID_FAVORITE_ORGANIZE            32803
#define ID_FAVORITE_DUMMY               32804
#define ID_ADD_FAVORITE                 32805
#define ID_ORGANIZE_FAVORITE            32806
#define ID_BF_BACK1                     32807
#define ID_BF_BACK2                     32808
#define ID_BF_BACK3                     32809
#define ID_BF_BACK4                     32810
#define ID_BF_BACK5                     32811
#define ID_BF_BACK6                     32812
#define ID_BF_BACK7                     32813
#define ID_BF_BACK8                     32814
#define ID_BF_BACK9                     32815
#define ID_BF_BACK_END                  32816
#define ID_CLOSE_WND_HISTORY_DUMMY      32818
#define ID_BF_FORWARD1                  32820
#define ID_BF_FORWARD2                  32821
#define ID_BF_FORWARD3                  32822
#define ID_BF_FORWARD4                  32823
#define ID_BF_FORWARD5                  32824
#define ID_BF_FORWARD6                  32825
#define ID_BF_FORWARD7                  32826
#define ID_BF_FORWARD8                  32827
#define ID_BF_FORWARD9                  32828
#define ID_BF_FORWARD_END               32829
#define ID_FILE_SAVEAS                  32847
#define ID_FULL_SCREEN                  32849
#define ID_W_CLOSE                      32850
#define ID_PREV_WND                     32853
#define ID_NEXT_WND                     32854
#define IDC_APP_EXIT                    32857
#define IDC_APP_EXIT_BUT_THIS           32858
#define ID_WINDOW_DUMMY                 32859
#define ID_CASCADE_WND                  32860
#define ID_TILE_V_WND                   32861
#define ID_TILE_H_WND                   32862
#define ID_MAXIMIZE_V_WND               32863
#define ID_MAXIMIZE_H_WND               32864
#define ID_MINIMIZE_ALL                 32865
#define ID_TOPMOST_WND                  32866
#define ID_TOPMOST_REL_WND              32867
#define ID_TOPMOST_SET                  32868
#define ID_RESTORE_WND                  32869
#define ID_SAVE_WND                     32870
#define ID_OPEN_THIN_FILER              32871
#define ID_NEW_BLANK                    32872
#define ID_TAB_CLOSE_RIGHT              32873
#define ID_TAB_CLOSE_LEFT               32874
#define ID_NEW_BLANK_TAB                32875
#define ID_TAB_LIST                     32876
#define ID_REOPEN_CLOSE_TAB             32877
#define ID_ZOOM_START                   32900
#define ID_ZOOM_END                     33000
#define ID_SEL_TAB_1                    33001
#define ID_SEL_TAB_2                    33002
#define ID_SEL_TAB_3                    33003
#define ID_SEL_TAB_4                    33004
#define ID_SEL_TAB_5                    33005
#define ID_SEL_TAB_6                    33006
#define ID_SEL_TAB_7                    33007
#define ID_SEL_TAB_8                    33008
#define ID_SEL_TAB_LAST                 33009
#define ID_ZOOM_UP                      33010
#define ID_ZOOM_DOWN                    33011
#define ID_ZOOM_RESET                   33012
#define IDC_APP_DELETE_CACHE            33013
#define ID_SETTING_OK                   36610

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        227
#define _APS_NEXT_COMMAND_VALUE         33015
#define _APS_NEXT_CONTROL_VALUE         1094
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
