//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// Sazabi.rc で使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDM_APP_EXIT                    0x0020
#define IDM_TASK_MGR                    0x0040
#define IDR_MAINFRAME                   128
#define IDR_SGSECITYPE                  129
#define IDS_STRING_DLG1                 130
#define IDD_DIALOG2                     131
#define IDS_STRING_DLG2                 132
#define IDS_STRING_DLG3                 133
#define IDS_STRING_FRM1                 134
#define IDS_STRING_FRM2                 135
#define IDR_HTML_DLGEULA                136
#define IDS_STRING_FRM3                 137
#define IDS_STRING_CEF_LIC              138
#define IDS_STRING_FAV_NANE             139
#define IDD_DIALOG1                     140
#define IDR_MENU_BACK                   141
#define IDR_MENU_FORWARD                142
#define IDB_BITMAP3                     143
#define IDI_ICON1                       144
#define IDB_COLDTOOLBAR                 146
#define IDB_HOTTOOLBAR                  147
#define IDR_TOOLBAR1                    150
#define IDB_BITMAP4                     151
#define IDB_BITMAP1                     152
#define IDD_DIALOG3                     153
#define IDB_CLOSE                       155
#define IDB_MAX                         156
#define IDB_MIN                         157
#define IDD_SETTINGS_DLG_URL_FILTER     159
#define IDS_STRING_CLOSE_ALL_WINDOW     160
#define IDS_STRING_ADMIN_LOCK_FEATURE   161
#define IDS_STRING_EVALUATION           162
#define IDS_STRING_EVALUATION_THANKS    163
#define IDS_STRING_ZONE_MSG_DBL         164
#define IDS_STRING_ZONE_MSG_NG          165
#define IDD_SETTINGS_DLG                167
#define IDD_SETTINGS_DLG_LOG            168
#define IDD_SETTINGS_DLG_DSP            171
#define IDD_SETTINGS_DLG_SEC            172
#define IDD_SETTINGS_DLG_INIT           173
#define IDD_SETTINGS_DLG_FILEMGR        174
#define IDS_STRING_ZONE_MSG_IE          184
#define IDD_DLG_AUTH                    185
#define IDS_STRING_ZONE_MSG_FF          186
#define IDB_BITMAP2                     187
#define IDB_BMP_KEY                     188
#define IDS_STRING_ZONE_MSG_CHR         189
#define IDS_STRING_ZONE_MSG_EDG         190
#define IDD_DIALOG4                     191
#define IDD_DLG_DEBUG_WND               193
#define IDB_BMP_DL                      194
#define IDS_STRING_ZONE_MSG_CUSTOM      195
#define IDB_BITMAP5                     196
#define IDS_STRING_DISABLE_EXEC         197
#define IDR_MENU1                       198
#define IDR_MENU_TAB                    199
#define IDB_BITMAP6                     200
#define IDD_DLG_SC_EDITOR               201
#define IDD_SETTINGS_DLG_CONNECTION     202
#define IDS_STRING_AUTO_RECOVERY        203
#define IDD_SETTINGS_DLG_GEN            204
#define IDS_STRING_UNDO                 205
#define IDD_SETTINGS_DLG_CAP            206
#define IDS_STRING_CUT                  207
#define IDS_STRING_COPY                 208
#define IDS_STRING_PASTE                209
#define IDS_STRING_DELETE               210
#define IDS_STRING_SELECTALL            211
#define IDS_STRING_PASTE_GO             212
#define IDS_STRING_PASTE_SEARCH         213
#define IDS_STRING_GO                   214
#define IDS_STRING_SEARCH               215
#define IDS_STRING_SEL_SEARCH           216
#define IDS_STRING_OPEN_NOACTIVE        217
#define IDS_STRING_SETTINGS             218
#define IDD_DIALOG5                     219
#define IDD_SETTINGS_DLG_CUSTOM_SCRIPT  220
#define IDD_DIALOG6                     221
#define IDD_DLG_AUTH_PWC                222
#define IDI_ICON2                       223
#define IDI_ICON3                       224
#define IDS_STRING_STARTING_BROWSER                  225
#define IDS_STRING_SETTINGS_DLG_TITLE_GEN            226
#define IDS_STRING_SETTINGS_DLG_TITLE_DSP            227
#define IDS_STRING_SETTINGS_DLG_TITLE_INIT           228
#define IDS_STRING_SETTINGS_DLG_TITLE_CONNECTION     229
#define IDS_STRING_SETTINGS_DLG_TITLE_CAP            230
#define IDS_STRING_SETTINGS_DLG_TITLE_SEC            231
#define IDS_STRING_SETTINGS_DLG_TITLE_URL_FILTER     232
#define IDS_STRING_SETTINGS_DLG_TITLE_SUSTOM_SCRIPT  233
#define IDS_STRING_SETTINGS_DLG_TITLE_LOG            234
#define IDS_STRING_SETTINGS_DLG_TITLE_FILEMGR        235
#define ID_SETTINGS_COLUMN_HEADER_URL                236
#define ID_SETTINGS_COLUMN_HEADER_DOMAIN             237
#define ID_SETTINGS_COLUMN_HEADER_FILE               238
#define ID_SETTINGS_COLUMN_HEADER_ACTION             239
#define ID_SETTINGS_COLUMN_HEADER_ENABLED            240
#define ID_SETTINGS_MENU_LABEL                       241
#define IDS_STRING_CONFIRM_CANCEL_DOWNLOAD           242
#define IDS_STRING_WELCOME_MSG                       243
#define IDS_STRING_STARTING_FILEMGR                  244
#define IDS_STRING_CONFIRM_CLEAR_CACHE               245
#define IDS_STRING_STARTING_NEW_SESSION              246
#define ID_OPEN_FILE_CHOOSER_TITLE                   247
#define ID_MSG_FILE_DOWNLOAD_RESTRICTED              248
#define ID_MSG_ANOTHER_DOWNLOAD_IN_PROGRESS          249
#define ID_DEFAULT_FILE_BASENAME                     250
#define ID_FILE_TYPE_ALL                             251
#define ID_FILE_TYPE_PDF                             252
#define ID_FILE_TYPE_EXE                             253
#define ID_FILE_TYPE_JS                              254
#define ID_DOWNLOAD_FILE_CHOOSER_TITLE               255
#define ID_PRINT_TO_PDF_FILE_CHOOSER_TITLE           256
#define ID_DEFAULT_FILE_DOWNLOAD_WINDOW_TITLE        257
#define ID_PRINT_TO_PDF_FINISH_MSG                   258
#define ID_DOWNLOAD_PROGRESS_DIALOG_TITLE            259
#define ID_TRANSFER_SPEED_B                          260
#define ID_TRANSFER_SPEED_KB                         261
#define ID_TRANSFER_SPEED_MB                         262
#define ID_TRANSFER_SIZE_UNDEFERMINED                263
#define ID_TRANSFER_PROGRESS_MSG                     264
#define ID_CONFIRM_CANCEL_DOWNLOAD                   265
#define ID_DL_START_APP_IN_PROGRESS                  267
#define ID_DL_START_APP_FAILED_BASE                  268
#define ID_DL_START_APP_FAILED_LOW_RESOURCE          269
#define ID_DL_START_APP_FAILED_FILE_NOT_FOUND        270
#define ID_DL_START_APP_FAILED_PATH_NOT_FOUND        271
#define ID_DL_START_APP_FAILED_BAD_FORMAT            272
#define ID_DL_START_APP_FAILED_ACCESSDENIED          273
#define ID_DL_START_APP_FAILED_ASSOCINCOMPLETE       274
#define ID_DL_START_APP_FAILED_DDEBUSY               275
#define ID_DL_START_APP_FAILED_DDEFAIL               276
#define ID_DL_START_APP_FAILED_DDETIMEOUT            277
#define ID_DL_START_APP_FAILED_DLLNOTFOUND           278
#define ID_DL_START_APP_FAILED_NOASSOC               279
#define ID_DL_START_APP_FAILED_OOM                   280
#define ID_DL_START_APP_FAILED_SHARE                 281
#define ID_DL_START_APP_FAILED_DEFAULT               282
#define ID_DOWNLOAD_COMPLETE_DIALOG_CLOSE            283
#define ID_DOWNLOAD_COMPLETE_DIALOG_TITLE            284
#define IDS_STRING_HOST_AUTH_REQUIRED                285
#define IDS_STRING_PROXY_AUTH_REQUIRED               286
#define IDS_STRING_CONFIRM_INSECURE_CONNECTION       287
#define IDS_STRING_CONFIRM_LEAVE_PAGE                288
#define IDS_STRING_ALERT_MISSING_FILES               289
#define IDS_STRING_CLEARING_CACHE                    290
#define IDS_STRING_CONFIRM_CLOSE_APPLICATION         291
#define IDS_STRING_TOO_MANY_WINDOWS_MSG              292
#define IDS_STRING_LOW_SYSTEM_RESOURCE_EXIT          293
#define IDS_STRING_LOW_SYSTEM_RESOURCE_SHUTDOWN      294
#define IDS_STRING_LOW_SYSTEM_RESOURCE_SUGGEST       295
#define IDS_STRING_CONFIRM_CLOSE_VOS_PROCESS         296
#define ID_CONTEXT_MENU_OPEN_LINK_TAB                297
#define ID_CONTEXT_MENU_OPEN_LINK_TAB_INACTIVE       298
#define ID_CONTEXT_MENU_OPEN_LINK_WINDOW             299
#define ID_CONTEXT_MENU_OPEN_LINK_WINDOW_INACTIVE    300
#define ID_CONTEXT_MENU_COPY_LINK                    301
#define ID_CONTEXT_MENU_SAVE_LINK                    302
#define ID_CONTEXT_MENU_OPEN_IMG_TAB                 303
#define ID_CONTEXT_MENU_OPEN_IMG_TAB_INACTIVE        304
#define ID_CONTEXT_MENU_OPEN_IMG_WINDOW              305
#define ID_CONTEXT_MENU_OPEN_IMG_WINDOW_INACTIVE     306
#define ID_CONTEXT_MENU_SAVE_IMG                     307
#define ID_CONTEXT_MENU_COPY_IMG                     308
#define ID_CONTEXT_MENU_COPY_IMG_LINK                309
#define ID_CONTEXT_MENU_SEARCH                       310
#define ID_CONTEXT_MENU_RELOAD                       311
#define ID_CONTEXT_MENU_PRINT_PDF                    312
#define ID_CONTEXT_MENU_PRINT                        313
#define ID_ERROR_MSG_FAILED                          314
#define ID_ERROR_MSG_NONE                            315
#define ID_ERROR_MSG_ABORTED                         316
#define ID_ERROR_MSG_INVALID_ARGUMENT                317
#define ID_ERROR_MSG_INVALID_HANDLE                  318
#define ID_ERROR_MSG_FILE_NOT_FOUND                  319
#define ID_ERROR_MSG_TIMED_OUT                       320
#define ID_ERROR_MSG_FILE_TOO_BIG                    321
#define ID_ERROR_MSG_UNEXPECTED                      322
#define ID_ERROR_MSG_ACCESS_DENIED                   323
#define ID_ERROR_MSG_NOT_IMPLEMENTED                 324
#define ID_ERROR_MSG_CONNECTION_CLOSED               325
#define ID_ERROR_MSG_CONNECTION_RESET                326
#define ID_ERROR_MSG_CONNECTION_REFUSED              327
#define ID_ERROR_MSG_CONNECTION_ABORTED              328
#define ID_ERROR_MSG_CONNECTION_FAILED               329
#define ID_ERROR_MSG_NAME_NOT_RESOLVED               330
#define ID_ERROR_MSG_INTERNET_DISCONNECTED           331
#define ID_ERROR_MSG_SSL_PROTOCOL_ERROR              332
#define ID_ERROR_MSG_ADDRESS_INVALID                 333
#define ID_ERROR_MSG_ADDRESS_UNREACHABLE             334
#define ID_ERROR_MSG_SSL_CLIENT_AUTH_CERT_NEEDED     335
#define ID_ERROR_MSG_TUNNEL_CONNECTION_FAILED        336
#define ID_ERROR_MSG_NO_SSL_VERSIONS_ENABLED         337
#define ID_ERROR_MSG_SSL_VERSION_OR_CIPHER_MISMATCH  338
#define ID_ERROR_MSG_SSL_RENEGOTIATION_REQUESTED     339
#define ID_ERROR_MSG_CERT_COMMON_NAME_INVALID        340
#define ID_ERROR_MSG_CERT_DATE_INVALID               341
#define ID_ERROR_MSG_CERT_AUTHORITY_INVALID          342
#define ID_ERROR_MSG_CERT_CONTAINS_ERRORS            343
#define ID_ERROR_MSG_CERT_NO_REVOCATION_MECHANISM    344
#define ID_ERROR_MSG_CERT_UNABLE_TO_CHECK_REVOCATION 345
#define ID_ERROR_MSG_CERT_REVOKED                    346
#define ID_ERROR_MSG_CERT_INVALID                    347
#define ID_ERROR_MSG_CERT_WEAK_SIGNATURE_ALGORITHM   348
#define ID_ERROR_MSG_CERT_NON_UNIQUE_NAME            349
#define ID_ERROR_MSG_CERT_WEAK_KEY                   350
#define ID_ERROR_MSG_CERT_NAME_CONSTRAINT_VIOLATION  351
#define ID_ERROR_MSG_CERT_VALIDITY_TOO_LONG          352
#define ID_ERROR_MSG_INVALID_URL                     353
#define ID_ERROR_MSG_DISALLOWED_URL_SCHEME           354
#define ID_ERROR_MSG_UNKNOWN_URL_SCHEME              355
#define ID_ERROR_MSG_TOO_MANY_REDIRECTS              356
#define ID_ERROR_MSG_UNSAFE_REDIRECT                 357
#define ID_ERROR_MSG_UNSAFE_PORT                     358
#define ID_ERROR_MSG_INVALID_RESPONSE                359
#define ID_ERROR_MSG_INVALID_CHUNKED_ENCODING        360
#define ID_ERROR_MSG_METHOD_NOT_SUPPORTED            361
#define ID_ERROR_MSG_UNEXPECTED_PROXY_AUTH           362
#define ID_ERROR_MSG_EMPTY_RESPONSE                  363
#define ID_ERROR_MSG_RESPONSE_HEADERS_TOO_BIG        364
#define ID_ERROR_MSG_CACHE_MISS                      365
#define ID_ERROR_MSG_INSECURE_RESPONSE               366
#define ID_ERROR_MSG_PROXY_CONNECTION_FAILED         367
#define ID_ERROR_PAGE_TITLE                          368
#define ID_ERROR_PAGE_HEADING                        369
#define ID_ERROR_PAGE_HEADING_DETAILS                370
#define ID_ERROR_PAGE_HEADING_URL                    371
#define ID_ERROR_PAGE_HEADING_CODE                   372
#define ID_ERROR_PAGE_HEADING_MSG                    373
#define ID_ERROR_PAGE_HEADING_NAME                   374
#define ID_ERROR_MISMATCHED_PARAMTER                 375
#define ID_ALERT_CANNOT_SAVE_CONFIGS                 376
#define ID_KEY_COMBINATION_EMPTY                     377
#define ID_KEY_COMBINATION_CONFIRM                   378
#define ID_KEY_COMBINATION_SUCCEEDED                 379
#define ID_KEY_COMBINATION_FAILED                    380
#define ID_ACTION_LABEL_ALLOW                        381
#define ID_ACTION_LABEL_DENY                         382
#define ID_CANNOT_SAVE_URL_FILTER                    383
#define ID_CANNOT_LOAD_CUSTOM_SCRIPT                 384
#define ID_CANNOT_SAVE_CUSTOM_SCRIPT                 385
#define ID_ALERT_ALREADY_ADDED_DOMAIN                386
#define ID_ALERT_ALREADY_ADDED_URL_OR_FILE           387
#define ID_ALERT_EMPTY_URL                           388
#define ID_ALERT_EMPTY_FILENAME                      389
#define ID_ALERT_EMPTY_DOMAIN                        390
#define ID_INFO_DLG_LIST_HIDE                        391
#define ID_INFO_DLG_LIST_0_5                         392
#define ID_INFO_DLG_LIST_1_0                         393
#define ID_INFO_DLG_LIST_1_5                         394
#define ID_INFO_DLG_LIST_2_0                         395
#define ID_INFO_DLG_LIST_2_5                         396
#define ID_INFO_DLG_LIST_3_0                         397
#define ID_INFO_DLG_LIST_3_5                         398
#define ID_INFO_DLG_LIST_4_0                         399
#define ID_INFO_DLG_LIST_4_5                         400
#define ID_INFO_DLG_LIST_5_0                         401
#define ID_INFO_DLG_LIST_5_5                         402
#define ID_INFO_DLG_LIST_6_0                         403
#define ID_INFO_DLG_LIST_6_5                         404
#define ID_INFO_DLG_LIST_7_0                         405
#define ID_INFO_DLG_LIST_7_5                         406
#define ID_INFO_DLG_LIST_8_0                         407
#define ID_INFO_DLG_LIST_8_5                         408
#define ID_INFO_DLG_LIST_9_0                         409
#define ID_INFO_DLG_LIST_9_5                         410
#define ID_INFO_DLG_LIST_10_0                        411
#define ID_INFO_OPEN_OPTION_HIDE_MARK_AS_OPENED      412
#define ID_INFO_OPEN_OPTION_SHOW_MARK_AS_OPENED      413
#define ID_INFO_OPEN_OPTION_SHOW_TRANSFER            414
#define ID_MISSING_PROXY_CONFIG                      415
#define ID_AUTH_ALERT_EMPTY_USER                     416
#define ID_AUTH_REQUIRED                             417
#define ID_AUTH_ALERT_MISMATCHED_PASSWORD            418
#define ID_AUTH_CHANGE_PASSWORD                      419
#define ID_DEBUG_ITEMS_COUNT                         420
#define ID_DEBUG_LINES_COUNT                         421
#define ID_DEBUG_CONFIRM_SAVE_RESULT                 422
#define ID_DEBUG_ALERT_SAVE_FAILED                   423
#define IDS_STRING_ALERT_OVER_RUNNING_TIME_LIMIT     424
#define IDC_EDIT1                       1000
#define IDC_EDIT_PW                     1001
#define IDC_EDIT2                       1002
#define IDC_CHECK1                      1006
#define IDC_B_SETTING                   1007
#define IDC_STATIC_LOGO                 1008
#define IDC_CHECK_ENABLE_LOG            1011
#define IDC_RADIO_LOG_ALL               1012
#define IDC_RADIO_LOG_NOFILE            1013
#define IDC_RADIO_LOG_GE_URL            1014
#define IDC_RADIO1                      1015
#define IDC_STATIC_TL                   1016
#define IDC_ExtFilter                   1017
#define IDC_EDIT_ZOOM                   1018
#define IDC_ShowUploadTab               1019
#define IDC_CHECK_ENABLE_CUSTOM_SCRIPT  1020
#define IDC_UploadSyncInterval          1021
#define IDC_EnableOpendOp               1022
#define IDC_EnableUploadSync            1023
#define IDC_EDIT_PW_NEW                 1024
#define IDC_EDIT_PW_NEW2                1025
#define IDC_EDIT_INIT_MSG               1026
#define IDC_CHECK_ENABLE_AUTO_ADJUST_WINPOS 1027
#define IDC_EDIT_W                      1030
#define IDC_EDIT_H                      1031
#define IDC_STATIC_MSG                  1032
#define IDC_EDIT_ID                     1033
#define IDC_EDIT_BW_LIST                1034
#define IDC_STATIC_FN                   1035
#define IDC_STATIC_TX                   1036
#define IDC_PROGRESS1                   1037
#define IDC_RADIO2                      1038
#define IDC_RootPath                    1039
#define IDC_STATIC_DL_MSG               1040
#define IDC_DisallowExt                 1041
#define IDC_TransferPath                1042
#define IDC_TransferSubFolder           1043
#define IDC_UploadPath                  1044
#define IDC_EDIT_SEARCH                 1045
#define IDC_DisableOpendOpAlert         1046
#define IDC_SetShowUploadTab            1047
#define IDC_EDIT_PW_CURRENT             1048
#define IDC_CHECK_DISABLE_MULTIPLE_INSTANCE 1049
#define IDC_EnableUploadSyncMirror      1050
#define IDC_EDIT_INIT_URL_PARAM         1052
#define IDC_EDIT_INIT_OP_PARAM          1053
#define IDC_CHECK_SHOW_PRINTER_BUTTON   1054
#define IDC_CHECK_GPU                   1055
#define IDC_CHECK_TAB                   1056
#define IDC_CHECK_LOGO                  1057
#define IDC_CHECK_PDF                   1058
#define IDC_CHECK_DISABLE_REBAR         1059
#define IDC_CHECK_DISABLE_STATUSBAR     1060
#define IDC_CHECK_DISABLE_STATUS_ICON   1061
#define IDC_CHECK_FLASH                 1062
#define IDC_CHECK_DISABLE_FILE_NAVIGATION 1065
#define IDC_COMBO1                      1084
#define IDC_BUTTON_FUNC                 1089
#define IDC_BUTTON_URL                  1090
#define IDC_BUTTON_TOP                  1091
#define IDC_BUTTON_TB_TRACE_LOG         1093
#define IDC_PAGE_FRAME                  1200
#define IDC_TREE_CTRL                   1201
#define IDC_CAPTION_BAR                 1202
#define ID_INDICATOR_ICON               1250
#define ID_INDICATOR_PROCESS            1251
#define ID_INDICATOR_SSL                1252
#define ID_INDICATOR_ZONE               1253
#define ID_INDICATOR_COMPAT             1254
#define ID_INDICATOR_ZOOM               1255
#define IDC_CHK_SHIFT                   1257
#define IDC_CHK_CTRL                    1258
#define IDC_CHK_ALT                     1259
#define IDC_CHK_LEFT                    1260
#define IDC_CHK_UP                      1261
#define IDC_CHK_RIGHT                   1262
#define IDC_CHK_DOWN                    1263
#define IDC_BUTTON1                     1264
#define IDC_BUTTON_FO                   1265
#define IDC_BUTTON_DIRO                 1266
#define IDC_RAD_PX_IE                   1267
#define IDC_RAD_PX_NA                   1268
#define IDC_RAD_PX_EF                   1269
#define IDC_EDIT_ProxyAddress           1270
#define IDC_EDIT_ProxyBypassAddress     1271
#define IDC_CHECK_ENABLE_URL_FILTER     1272
#define IDC_LIST1                       1273
#define IDC_BUTTON_INS                  1274
#define IDC_BUTTON_DEL                  1275
#define IDC_BUTTON_UP                   1276
#define IDC_BUTTON_DOWN                 1277
#define IDC_STATIC_LINE                 1278
#define IDC_UserAgentAppendStr          1279
#define IDC_MemoryUsageWarning          1280
#define IDC_MemoryUsageLimit            1281
#define IDC_WindowCountWarning          1282
#define IDC_CHECK_ENABLECRASHRECOVERY   1328
#define IDC_ENABLE_MEMCACHE             1340
#define IDC_Enable_ProcessRunTime       1344
#define IDC_EDIT_LIMIT_TIME             1345
#define IDC_VOS_CLOSE_PROCESS           1346
#define IDC_EnableUploadRestriction     1346
#define IDC_SHOW_DEV_TOOLS              1347
#define IDC_EnableDownloadRestriction   1347
#define IDC_EDIT_CustomBrowser1         1348
#define IDC_EnableDeleteCache           1348
#define IDC_CEF_VERSION                 1348
#define IDC_CHECK_EnableZoneFilterScript 1349
#define IDC_BUTTON_BROWSE1              1350
#define IDC_BUTTON_SCRIPT_EDIT          1351
#define IDC_EDIT_CustomBrowser2         1352
#define IDC_BUTTON_BROWSE2              1353
#define IDC_EDIT_CustomBrowser3         1354
#define IDC_BUTTON_BROWSE3              1355
#define IDC_EDIT_CustomBrowser4         1356
#define IDC_BUTTON_BROWSE4              1357
#define IDC_EDIT_CustomBrowser5         1358
#define IDC_BUTTON_BROWSE5              1359
#define IDC_WindowCountLimit            1360
#define IDC_STATIC_LOGO_ABOUT           1361
#define IDC_CHECK_EnableLogging         1362
#define IDC_EDIT_LogServerURL           1363
#define IDC_RADIO_LOG_GET               1364
#define IDC_RADIO_LOG_POST              1365
#define IDC_CHECK_ENABLE_DOWNLOAD_LOG   1366
#define IDC_CHECK_ENABLE_UPLOAD_LOG     1367
#define IDC_CHECK_EnableBrowsingLogging 1368
#define IDC_CHECK_EnableAccessAllLogging 1369
#define IDC_EDIT_RequestHeader          1370
#define ID_SETTINGS                     32609
#define IDD_ABOUTBOX                    32771
#define ID_NEW                          32772
#define ID_PRINT                        32773
#define ID_LOGIN                        32774
#define ID_GO_BACK                      32776
#define ID_GO_FORWARD                   32777
#define ID_VIEW_STOP                    32778
#define ID_VIEW_REFRESH                 32779
#define ID_GO_START_PAGE                32780
#define ID_OPEN                         32781
#define ID_SHOW_DEVTOOLS                32782
#define ID_PRINT_PDF                    32783
#define ID_CUT                          32784
#define ID_COPY                         32785
#define ID_PASTE                        32786
#define ID_SEL_ALL                      32787
#define ID_FIND_PAGE                    32788
#define ID_SET_ADDRESSBAR               32797
#define ID_NEW_SESSION                  32798
#define ID_SET_SEARCHBAR                32799
#define ID_FAVORITE_ADD                 32802
#define ID_FAVORITE_ORGANIZE            32803
#define ID_FAVORITE_DUMMY               32804
#define ID_ADD_FAVORITE                 32805
#define ID_ORGANIZE_FAVORITE            32806
#define ID_BF_BACK1                     32807
#define ID_BF_BACK2                     32808
#define ID_BF_BACK3                     32809
#define ID_BF_BACK4                     32810
#define ID_BF_BACK5                     32811
#define ID_BF_BACK6                     32812
#define ID_BF_BACK7                     32813
#define ID_BF_BACK8                     32814
#define ID_BF_BACK9                     32815
#define ID_BF_BACK_END                  32816
#define ID_CLOSE_WND_HISTORY_DUMMY      32818
#define ID_BF_FORWARD1                  32820
#define ID_BF_FORWARD2                  32821
#define ID_BF_FORWARD3                  32822
#define ID_BF_FORWARD4                  32823
#define ID_BF_FORWARD5                  32824
#define ID_BF_FORWARD6                  32825
#define ID_BF_FORWARD7                  32826
#define ID_BF_FORWARD8                  32827
#define ID_BF_FORWARD9                  32828
#define ID_BF_FORWARD_END               32829
#define ID_FILE_SAVEAS                  32847
#define ID_FULL_SCREEN                  32849
#define ID_W_CLOSE                      32850
#define ID_PREV_WND                     32853
#define ID_NEXT_WND                     32854
#define IDC_APP_EXIT                    32857
#define IDC_APP_EXIT_BUT_THIS           32858
#define ID_WINDOW_DUMMY                 32859
#define ID_CASCADE_WND                  32860
#define ID_TILE_V_WND                   32861
#define ID_TILE_H_WND                   32862
#define ID_MAXIMIZE_V_WND               32863
#define ID_MAXIMIZE_H_WND               32864
#define ID_MINIMIZE_ALL                 32865
#define ID_TOPMOST_WND                  32866
#define ID_TOPMOST_REL_WND              32867
#define ID_TOPMOST_SET                  32868
#define ID_RESTORE_WND                  32869
#define ID_SAVE_WND                     32870
#define ID_OPEN_THIN_FILER              32871
#define ID_NEW_BLANK                    32872
#define ID_TAB_CLOSE_RIGHT              32873
#define ID_TAB_CLOSE_LEFT               32874
#define ID_NEW_BLANK_TAB                32875
#define ID_TAB_LIST                     32876
#define ID_REOPEN_CLOSE_TAB             32877
#define ID_ZOOM_START                   32900
#define ID_ZOOM_END                     33000
#define ID_SEL_TAB_1                    33001
#define ID_SEL_TAB_2                    33002
#define ID_SEL_TAB_3                    33003
#define ID_SEL_TAB_4                    33004
#define ID_SEL_TAB_5                    33005
#define ID_SEL_TAB_6                    33006
#define ID_SEL_TAB_7                    33007
#define ID_SEL_TAB_8                    33008
#define ID_SEL_TAB_LAST                 33009
#define ID_ZOOM_UP                      33010
#define ID_ZOOM_DOWN                    33011
#define ID_ZOOM_RESET                   33012
#define IDC_APP_DELETE_CACHE            33013
#define ID_SETTING_OK                   36610

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        227
#define _APS_NEXT_COMMAND_VALUE         33015
#define _APS_NEXT_CONTROL_VALUE         1094
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
